# Generated by Django 5.0.7 on 2024-08-15 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_messagefromcustomer_usersubscribe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSubscribe',
            new_name='Subscriber',
        ),
    ]
