# Generated by Django 5.0.7 on 2024-08-13 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommonOptions',
            new_name='CommonOption',
        ),
        migrations.RenameModel(
            old_name='Counters',
            new_name='Counter',
        ),
        migrations.RenameModel(
            old_name='Testimonials',
            new_name='Testimonial',
        ),
    ]
