# Generated by Django 5.0.7 on 2024-08-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_commonoptions_commonoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, upload_to='testimonial_photos'),
        ),
        migrations.AlterField(
            model_name='commonoption',
            name='key',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
