# Generated by Django 5.0.7 on 2024-08-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_testimonial_photo_alter_commonoption_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
