# Generated by Django 5.0.7 on 2024-08-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_counter_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonoption',
            name='value',
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
