# Generated by Django 5.0.7 on 2024-08-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_commonoption_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='last_name',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name',
            field=models.CharField(default='Python', max_length=64),
            preserve_default=False,
        ),
    ]
