# Generated by Django 5.0.7 on 2024-08-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_dish_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='weight',
        ),
        migrations.AlterField(
            model_name='dish',
            name='sort',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
